name: Build repository wiki

on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths:
            - 'docs/wiki/**'

env:
    wiki_source: "${{ github.repository }}"
    wiki_source_repo_dir: "docs/wiki"
    wiki_target_repo: "${{ github.repository }}.wiki"
    github_user_name: "github-actions"
    github_email: "${{ github.actor }}@users.noreply.github.com"
    github_commit_message: "Wiki Sync from docs/wiki area of main branch"

jobs:
  build-wiki:
    name: Build wiki
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout Source Repo
        uses: actions/checkout@1fb4a623cfbc661771f7005e00e2cf74acf32037   # v4.2.2
        with:
          repository: ${{ env.wiki_source }}
          path: ${{ github.workspace }}/source

      - name: Checkout Wiki Repo
        uses: actions/checkout@1fb4a623cfbc661771f7005e00e2cf74acf32037   # v4.2.2
        with:
          repository: ${{ env.wiki_target_repo }}
          path: ${{ github.workspace }}/wiki

      - name: Configure Local Git
        run: |
          git config --global user.name $github_user_name
          git config --global user.email $github_email
        working-directory: ${{ github.workspace }}

      - name: Create Target Directory
        run: mkdir -p ${{ github.workspace }}/wiki

      - name: Sync Source Folder to Wiki Repo
        run: rsync -avzr --delete --exclude='.git' ${{ github.workspace }}/source/${{ env.wiki_source_repo_dir }}/ ${{ github.workspace }}/wiki/
        working-directory: ${{ github.workspace }}

      - name: Stage & Push Files Into Wiki Repo
        run: |
          cd ${{ github.workspace }}/wiki
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "$github_commit_message [$GITHUB_ACTOR/${GITHUB_SHA::8}]"
            git push --set-upstream https://$GITHUB_TOKEN@github.com/${{ env.wiki_target_repo }}.git master
          else
            echo "No changes to commit"
          fi
        working-directory: ${{ github.workspace }}/wiki